# -*- coding: utf-8 -*-
"""location

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DzrmFYf31KE95ktkV_fjucWY9ELwIqqj
"""

import requests

# List of people with their addresses
people = [
    {"name": "prime", "address": "Nageshwar Nagar moshi,bhosari,india", "wants_tractor": True},
    {"name": "Sanku", "address": "DY patil akurdi,pune,india", "wants_tractor": False},
    {"name": "harsha", "address": "near ojas hospital,bhondave chowk ravet,pune,india", "wants_tractor": True},
    {"name": "adya", "address": "gurudawra choek,near akurdi railway station,akurdi,india", "wants_tractor": False},
    {"name": "rushikesh", "address": "sadhuram garden gandhrw nagari,moshi,pune,india", "wants_tractor": True}
]

# OpenCage Geocoder API endpoint and API key
geocoder_endpoint = "https://api.opencagedata.com/geocode/v1/json"
geocoder_api_key = "8e1d04c8640f461eb852a9f44c79387e"

# Loop through each person and get their latitude and longitude coordinates
for person in people:
    address = person["address"]
    params = {"q": address, "key": geocoder_api_key}
    response = requests.get(geocoder_endpoint, params=params).json()
    if response["results"]:
        lat = response["results"][0]["geometry"]["lat"]
        lon = response["results"][0]["geometry"]["lng"]
        print(f"{person['name']} ({address}) is located at ({lat}, {lon})")
    else:
        print(f"Error: {address} not found")

